package:
    name: asvdb
    version: 0.1.6dev0

source:
    git_url: https://github.com/rlratzel/asvdb.git

build:
    number: 0
    noarch: python

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports:
        - asvdb

about:
    home: https://github.com/rlratzel/asvdb
    license: Apache 2.0
