package:
    name: asvdb
    version: 0.2.0dev0

source:
    #git_url: https://github.com/rlratzel/asvdb.git
    path: ..

build:
    number: 0

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports:
        - asvdb

about:
    home: https://github.com/rlratzel/asvdb
    license: Apache 2.0
